# Generated by Django 5.1.1 on 2024-10-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumerologyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('life_path_number', models.CharField(blank=True, max_length=10, null=True)),
                ('destiny', models.CharField(blank=True, max_length=10, null=True)),
                ('soul_urge_number', models.CharField(blank=True, max_length=10, null=True)),
                ('personality_number', models.CharField(blank=True, max_length=10, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
